spring:
  datasource:
    url: jdbc:mariadb://${simple.datasource.ip}:${simple.datasource.port}/${simple.datasource.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${simple.datasource.username}
    password: ${simple.datasource.password}
    driver-class-name: org.mariadb.jdbc.Driver