gateway:
  route:
    dynamic: true

simple:
  auth:
    tokenMode: jwt
  security:
    denyPaths:
      - "/*/actuator/**"
      - "/*/micro/**"
    ignoreAuthPaths:
      - "/actuator/**"
      - "/simple-auth/oauth/token"
      - "/*/open/**"