spring:
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:9280
      log:
        dir: logs/${spring.application.name}/
      # 配置限流之后，响应内容
      scg:
        fallback:
          # 两种模式，一种是response返回文字提示信息，
          # 一种是redirect，重定向跳转，需要同时配置redirect(跳转的uri)
          mode: response
          # 响应的状态
          response-status: 200
          # 响应体
          response-body: '{"code": 9999,"message": "请求频繁，请稍后重试！"}'

gateway:
  route:
    dynamic: true

simple:
  auth:
    tokenMode: jwt
  security:
    denyPaths:
      - "/*/actuator/**"
      - "/*/micro/**"
    ignoreAuthPaths:
      - "/actuator/**"
      - "/simple-auth/oauth/token"
      - "/*/open/**"