project:
  datasource:
    ip: 127.0.0.1
    port: 3306
    username: root
    password: 123456

spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          password: 123456
          address: "redis://127.0.0.1:6379"
        threads: 0
        nettyThreads: 0
        transportMode: "NIO"

logging:
  level:
    per:
      qy:
        simple: debug